{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: backend-gateway-entry
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
    - {{ .Values.istio.domain }}
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
  resolution: STATIC
  endpoints:
    - address: {{ .Values.tailscale.backendIp }}
{{- end }}
