{{- if .Values.istio.enabled }}
{{- range $name, $config := .Values.services }}
{{- if not $config.command }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $name }}-dr
  namespace: {{ $.Values.namespace }}
spec:
  host: {{ $name }}
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
    outlierDetection:
      consecutive5xxErrors: 1
      interval: 1s
      baseEjectionTime: 1m
      maxEjectionPercent: 100
{{- end }}
{{- end }}
{{- end }}
