{{- if .Values.istio.enabled }}
{{- range $name, $config := .Values.services }}
{{- if $config.retry }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $name }}-vs
  namespace: {{ $.Values.namespace }}
spec:
  hosts:
    - {{ $name }}
  http:
    - route:
        - destination:
            host: {{ $name }}
      retries:
        attempts: {{ $config.retry.attempts }}
        perTryTimeout: {{ $config.retry.perTryTimeout }}
        retryOn: {{ $config.retry.retryOn | quote }}
{{- end }}
{{- end }}
{{- end }}
