# ==============================================================
# Namespace
# ==============================================================
namespace: test

# ==============================================================
# Istio settings
# ==============================================================
istio:
  enabled: true

# ==============================================================
# Services list to deploy and manage via Mesh
# ==============================================================
services:
  # --- UI / Edge ---
  storefront-ui:
    image: kennethreitz/httpbin
    port: 80
  backoffice-ui:
    image: kennethreitz/httpbin
    port: 80
  swagger-ui:
    image: kennethreitz/httpbin
    port: 80
  
  # --- BFF ---
  storefront-bff:
    image: kennethreitz/httpbin
    port: 80
    allowedCallers: ["storefront-ui", "swagger-ui"]
  backoffice-bff:
    image: kennethreitz/httpbin
    port: 80
    allowedCallers: ["backoffice-ui", "swagger-ui"]

  # --- Microservices ---
  product:
    image: kennethreitz/httpbin
    port: 80
    allowedCallers: ["storefront-bff", "backoffice-bff", "search", "sleep-client"]
    retry:
      attempts: 3
      perTryTimeout: 2s
      retryOn: "5xx,connect-failure,retriable-4xx"
  
  cart:
    image: kennethreitz/httpbin
    port: 80
    allowedCallers: ["storefront-bff", "order"]
    
  order:
    image: kennethreitz/httpbin
    port: 80
    allowedCallers: ["storefront-bff", "cart", "sleep-client"]
    
  customer:
    image: kennethreitz/httpbin
    port: 80
    allowedCallers: ["storefront-bff", "backoffice-bff", "order"]
    
  inventory:
    image: kennethreitz/httpbin
    port: 80
    allowedCallers: ["order", "backoffice-bff"]
    
  tax:
    image: kennethreitz/httpbin
    port: 80
    allowedCallers: ["order", "sleep-client"]
    retry:
      attempts: 3
      perTryTimeout: 2s
      retryOn: "5xx,connect-failure,retriable-4xx"
      
  media:
    image: kennethreitz/httpbin
    port: 80
    allowedCallers: ["product", "backoffice-bff"]
    
  search:
    image: kennethreitz/httpbin
    port: 80
    allowedCallers: ["storefront-bff", "product"]

  # --- Others ---
  sampledata:
    image: kennethreitz/httpbin
    port: 80
    
  sleep-client:
    image: curlimages/curl
    command: ["sleep", "infinity"]
