global:
  keycloak:
    issuerUri: http://infrastructure-keycloak/realms/Yas
  postgresql:
    username: admin
    password: admin
  kafka:
    bootstrapServers: infrastructure-kafka:9092
  redis:
    host: infrastructure-redis-master
    port: 6379
  elasticsearch:
    uris: http://infrastructure-elasticsearch:9200

storefront-nextjs:
  enabled: false
  image:
    repository: ducquan19/yas-storefront
    tag: main
    containerPort: 3000
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 3000
    nodePort: 30001
  env: {}
  secrets: {}

storefront-bff:
  enabled: false
  image:
    repository: ducquan19/yas-storefront-bff
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30002
  env: {}
  secrets: {}
  isBackend: true
  uiHost: "http://storefront-nextjs:3000"

backoffice-nextjs:
  enabled: false
  image:
    repository: ducquan19/yas-backoffice
    tag: main
    containerPort: 3000
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 3000
    nodePort: 30003
  env: {}
  secrets: {}

backoffice-bff:
  enabled: false
  image:
    repository: ducquan19/yas-backoffice-bff
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30004
  env: {}
  secrets: {}
  isBackend: true
  uiHost: "http://backoffice-nextjs:3000"

product:
  enabled: false
  image:
    repository: ducquan19/yas-product
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30005
  env: {}
  secrets: {}
  isBackend: true

media:
  enabled: false
  image:
    repository: ducquan19/yas-media
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30006
  env: {}
  secrets: {}
  isBackend: true

customer:
  enabled: false
  image:
    repository: ducquan19/yas-customer
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30007
  env: {}
  secrets: {}
  isBackend: true

cart:
  enabled: false
  image:
    repository: ducquan19/yas-cart
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30008
  env: {}
  secrets: {}
  isBackend: true

order:
  enabled: false
  image:
    repository: ducquan19/yas-order
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30009
  env: {}
  secrets: {}
  isBackend: true

inventory:
  enabled: false
  image:
    repository: ducquan19/yas-inventory
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30010
  env: {}
  secrets: {}
  isBackend: true

tax:
  enabled: false
  image:
    repository: ducquan19/yas-tax
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30011
  env: {}
  secrets: {}
  isBackend: true

search:
  enabled: false
  image:
    repository: ducquan19/yas-search
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30012
  env: {}
  secrets: {}
  isBackend: true

sampledata:
  enabled: false
  image:
    repository: ducquan19/yas-sampledata
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30013
  env: {}
  secrets: {}

swagger:
  enabled: false
  image:
    repository: swaggerapi/swagger-ui
    tag: v5.17.14
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: NodePort
    port: 8082
    nodePort: 30014
  env: {}
  secrets: {}

tailscale:
  backendIp: 100.91.182.4

istio:
  enabled: true
  domain: api.yas.local
