storefront:
  enabled: true
  image:
    tag: main

storefront-bff:
  enabled: true
  image:
    tag: main

backoffice:
  enabled: true
  image:
    tag: main

backoffice-bff:
  enabled: true
  image:
    tag: main

customer:
  enabled: true
  image:
    tag: main
