global:
  keycloak:
    issuerUri: http://infra-keycloak.infrastructure.svc.cluster.local/realms/Yas
  postgresql:
    username: admin
    password: admin
  kafka:
    bootstrapServers: infra-kafka.infrastructure.svc.cluster.local:9092
  redis:
    host: infra-redis.infrastructure.svc.cluster.local
    port: 6379
  elasticsearch:
    uris: http://infra-elasticsearch.infrastructure.svc.cluster.local:9200
storefront-nextjs:
  syncWave: 7
  enabled: true
  image:
    repository: ducquan19/yas-storefront
    tag: latest
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 3000
  env:
    NEXT_PUBLIC_API_BASE_PATH: https://storefront.yas.io
    API_BASE_PATH: http://storefront-bff:8082/api
storefront-bff:
  syncWave: 6
  enabled: true
  image:
    repository: ducquan19/yas-storefront-bff
    tag: latest
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  uiHost: https://storefront.yas.io
  isBackend: true
backoffice-nextjs:
  syncWave: 7
  enabled: true
  image:
    repository: ducquan19/yas-backoffice
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 3000
  env:
    NEXT_PUBLIC_API_BASE_PATH: https://backoffice.yas.io
    API_BASE_PATH: http://backoffice-bff:8082/api
backoffice-bff:
  syncWave: 6
  enabled: true
  image:
    repository: ducquan19/yas-backoffice-bff
    tag: latest
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  uiHost: https://backoffice.yas.io
  isBackend: true
product:
  syncWave: 2
  enabled: true
  image:
    repository: ducquan19/yas-product
    tag: latest
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
media:
  syncWave: 1
  enabled: true
  image:
    repository: ducquan19/yas-media
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
customer:
  syncWave: 1
  enabled: true
  image:
    repository: ducquan19/yas-customer
    tag: latest
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
cart:
  syncWave: 3
  enabled: false
  image:
    repository: ducquan19/yas-cart
    tag: latest
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
order:
  syncWave: 4
  enabled: true
  image:
    repository: ducquan19/yas-order
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
inventory:
  syncWave: 3
  enabled: true
  image:
    repository: ducquan19/yas-inventory
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
tax:
  syncWave: 1
  enabled: true
  image:
    repository: ducquan19/yas-tax
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
search:
  syncWave: 1
  enabled: true
  image:
    repository: ducquan19/yas-search
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
sampledata:
  syncWave: 5
  enabled: true
  image:
    repository: ducquan19/yas-sampledata
    tag: main
    containerPort: 8094
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8094
  env:
    SPRING_DATASOURCE_PRODUCT_URL: jdbc:postgresql://infra-postgresql.infrastructure.svc.cluster.local:5432/product
    SPRING_DATASOURCE_MEDIA_URL: jdbc:postgresql://infra-postgresql.infrastructure.svc.cluster.local:5432/media
    SPRING_DATASOURCE_USERNAME: admin
    SPRING_DATASOURCE_PASSWORD: admin
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://identity.yas.io/realms/Yas
    CORS_ALLOWED_ORIGINS: https://storefront.yas.io,https://backoffice.yas.io
swagger:
  syncWave: 7
  enabled: true
  image:
    repository: swaggerapi/swagger-ui
    tag: v5.17.14
    containerPort: 8080
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8080
  env:
    URLS: '[{ url: ''https://api.yas.io/product/v3/api-docs'', name: ''Product'' },{
      url: ''https://api.yas.io/media/v3/api-docs'', name: ''Media'' },{ url: ''https://api.yas.io/customer/v3/api-docs'',
      name: ''Customer'' },{ url: ''https://api.yas.io/cart/v3/api-docs'', name: ''Cart''
      },{ url: ''https://api.yas.io/order/v3/api-docs'', name: ''Order'' },{ url:
      ''https://api.yas.io/inventory/v3/api-docs'', name: ''Inventory'' },{ url: ''https://api.yas.io/location/v3/api-docs'',
      name: ''Location'' },{ url: ''https://api.yas.io/tax/v3/api-docs'', name: ''Tax''
      },{ url: ''https://api.yas.io/search/v3/api-docs'', name: ''Search'' },{ url:
      ''https://api.yas.io/payment/v3/api-docs'', name: ''Payment'' }]'
    OAUTH_CLIENT_ID: swagger-ui
    OAUTH_USE_PKCE: 'true'
istio:
  enabled: true
  domain: api.yas.io
tailscale:
  backendIp: "127.0.0.1"
location:
  syncWave: 2
  enabled: true
  image:
    repository: ducquan19/yas-location
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
payment:
  syncWave: 2
  enabled: true
  image:
    repository: ducquan19/yas-payment
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
rating:
  syncWave: 3
  enabled: true
  image:
    repository: ducquan19/yas-rating
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
recommendation:
  syncWave: 3
  enabled: true
  image:
    repository: ducquan19/yas-recommendation
    tag: main
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
  service:
    type: ClusterIP
    port: 8082
  isBackend: true
