global:
  domain: 54.179.218.151.nip.io
  keycloak:
    issuerUri: http://infra-keycloak.infrastructure.svc.cluster.local/realms/Yas
  postgresql:
    username: admin
    password: admin
  kafka:
    bootstrapServers: infra-kafka.infrastructure.svc.cluster.local:9092
  redis:
    host: infra-redis.infrastructure.svc.cluster.local
    port: 6379
  elasticsearch:
    uris: http://infra-elasticsearch.infrastructure.svc.cluster.local:9200
_ecr_prefix: ducquan19
storefront-bff:
  enabled: true
  image:
    repository: ducquan19/yas-storefront-bff
    tag: main
  uiHost: http://storefront-nextjs:3000
backoffice-bff:
  enabled: true
  image:
    repository: ducquan19/yas-backoffice-bff
    tag: main
  uiHost: http://backoffice-nextjs:3000
storefront-nextjs:
  enabled: true
  image:
    repository: ducquan19/yas-storefront
    tag: latest
  env:
    NEXT_PUBLIC_API_BASE_PATH: https://storefront.54.179.218.151.nip.io
    API_BASE_PATH: http://storefront-bff:8082/api
backoffice-nextjs:
  enabled: true
  image:
    repository: ducquan19/yas-backoffice
    tag: main
  env:
    NEXT_PUBLIC_API_BASE_PATH: https://backoffice.54.179.218.151.nip.io
    API_BASE_PATH: http://backoffice-bff:8082/api
swagger:
  enabled: true
  env:
    URLS: '[{ url: ''https://api.54.179.218.151.nip.io/api/product/v3/api-docs'', name: ''Product''
      },{ url: ''https://api.54.179.218.151.nip.io/api/media/v3/api-docs'', name: ''Media'' },{ url:
      ''https://api.54.179.218.151.nip.io/api/customer/v3/api-docs'', name: ''Customer'' },{ url:
      ''https://api.54.179.218.151.nip.io/api/cart/v3/api-docs'', name: ''Cart'' },{ url: ''https://api.54.179.218.151.nip.io/api/order/v3/api-docs'',
      name: ''Order'' },{ url: ''https://api.54.179.218.151.nip.io/api/inventory/v3/api-docs'', name:
      ''Inventory'' },{ url: ''https://api.54.179.218.151.nip.io/api/location/v3/api-docs'', name:
      ''Location'' },{ url: ''https://api.54.179.218.151.nip.io/api/tax/v3/api-docs'', name: ''Tax''
      },{ url: ''https://api.54.179.218.151.nip.io/api/search/v3/api-docs'', name: ''Search'' },{
      url: ''https://api.54.179.218.151.nip.io/api/payment/v3/api-docs'', name: ''Payment'' }]'
    OAUTH_CLIENT_ID: swagger-ui
    OAUTH_USE_PKCE: 'true'
product:
  enabled: true
  image:
    repository: ducquan19/yas-product
    tag: latest
cart:
  enabled: true
  image:
    repository: ducquan19/yas-cart
    tag: latest
order:
  enabled: true
  image:
    repository: ducquan19/yas-order
    tag: main
customer:
  enabled: true
  image:
    repository: ducquan19/yas-customer
    tag: latest
inventory:
  enabled: true
  image:
    repository: ducquan19/yas-inventory
    tag: main
media:
  enabled: true
  image:
    repository: ducquan19/yas-media
    tag: main
  initContainers:
    - name: copy-sample-images
      image: ducquan19/yas-sample-images:main
      command:
        - sh
        - -c
        - cp -R /sample-images/. /images/
      volumeMounts:
        - name: sample-images
          mountPath: /images
  extraVolumes:
    - name: sample-images
      emptyDir: {}
  extraVolumeMounts:
    - name: sample-images
      mountPath: /images
      readOnly: true
search:
  enabled: true
  image:
    repository: ducquan19/yas-search
    tag: main
tax:
  enabled: true
  image:
    repository: ducquan19/yas-tax
    tag: main
location:
  enabled: true
  image:
    repository: ducquan19/yas-location
    tag: main
payment:
  enabled: true
  image:
    repository: ducquan19/yas-payment
    tag: main
sampledata:
  enabled: true
  image:
    repository: ducquan19/yas-sampledata
    tag: main
  env:
    SPRING_DATASOURCE_PRODUCT_URL: jdbc:postgresql://infra-postgresql.infrastructure.svc.cluster.local:5432/product
    SPRING_DATASOURCE_MEDIA_URL: jdbc:postgresql://infra-postgresql.infrastructure.svc.cluster.local:5432/media
    SPRING_DATASOURCE_USERNAME: admin
    SPRING_DATASOURCE_PASSWORD: admin
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://identity.54.179.218.151.nip.io/realms/Yas
    CORS_ALLOWED_ORIGINS: https://storefront.54.179.218.151.nip.io,https://backoffice.54.179.218.151.nip.io

istio:
  enabled: true
  domain: api.54.179.218.151.nip.io

tailscale:
  backendIp: "54.179.218.151"
