{{- if .Values.letsencrypt.staging.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsencrypt.staging.name }}
spec:
  acme:
    {{- if .Values.letsencrypt.email }}
    email: {{ .Values.letsencrypt.email | quote }}
    {{- end }}
    server: {{ .Values.letsencrypt.staging.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.letsencrypt.staging.name }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.letsencrypt.ingressClassName | quote }}
{{- end }}
{{- if and .Values.letsencrypt.staging.enabled .Values.letsencrypt.production.enabled }}
---
{{- end }}
{{- if .Values.letsencrypt.production.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.letsencrypt.production.name }}
spec:
  acme:
    {{- if .Values.letsencrypt.email }}
    email: {{ .Values.letsencrypt.email | quote }}
    {{- end }}
    server: {{ .Values.letsencrypt.production.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.letsencrypt.production.name }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.letsencrypt.ingressClassName | quote }}
{{- end }}
