loki:
  enabled: true
  write:
    replicas: 1
    podSecurityContext:
      fsGroup: 10001
      runAsUser: 10001
  read:
    replicas: 1
    podSecurityContext:
      fsGroup: 10001
      runAsUser: 10001
  backend:
    replicas: 1
    podSecurityContext:
      fsGroup: 10001
      runAsUser: 10001
  loki:
    commonConfig:
      replication_factor: 1
    auth_enabled: false
  test:
    enabled: false
  storage:
    type: 'filesystem'
  minio:
    enabled: true
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
  persistence:
    storageClass: ebs-sc
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false

promtail:
  enabled: true
  config:
    clients:
      - url: http://observability-loki-gateway/loki/api/v1/push
  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 5

tempo:
  enabled: true
  persistence:
    storageClass: ebs-sc
  tempo:
    metricsGenerator:
      enabled: true
      remoteWriteUrl: "http://observability-kube-prometh-prometheus:9090/api/v1/write"

kube-prometheus-stack:
  enabled: true
  hostname: &hostname grafana.yas.local.com
  prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-sc
          resources:
            requests:
              storage: 20Gi
  grafana:
    enabled: true
    adminUser: admin
    adminPassword: admin
    additionalDataSources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway
        access: proxy
        jsonData:
          httpMethod: GET
          maxLines: 1000
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: traceId=(\w*)
              name: traceId
              url: ${__value.raw}
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://observability-tempo:3200
        access: proxy
        jsonData:
          httpMethod: GET
          tracesToLogsV2:
            datasourceUid: loki
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true


opentelemetry:
  enabled: true

kiali-server:
  enabled: true
  deployment:
    accessible_namespaces:
      - '**'
  auth:
    strategy: anonymous
  external_services:
    prometheus:
      url: "http://observability-kube-prometh-prometheus.observability:9090"
    istio:
      root_namespace: istio-system
    grafana:
      enabled: true
      url: "http://observability-grafana.observability:80"
  istio_namespace: istio-system
