# Enable dependencies
loki:
  enabled: true
  write:
    replicas: 1
  read:
    replicas: 1
  backend:
    replicas: 1
  loki:
    commonConfig:
      replication_factor: 1
    auth_enabled: false
  test:
    enabled: false
  storage:
    type: 'filesystem'
  minio:
    enabled: true
  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki-gateway/loki/api/v1/push
    snippets:
      pipelineStages:
        - docker: {}

tempo:
  enabled: true
  tempo:
    metricsGenerator:
      enabled: true
      remoteWriteUrl: "http://observability-kube-prometh-prometheus:9090/api/v1/write"

kube-prometheus-stack:
  enabled: true
  hostname: &hostname grafana.yas.local.com
  prometheus:
    prometheusSpec:
      enableRemoteWriteReceiver: true
  grafana:
    enabled: true
    adminUser: admin
    adminPassword: admin
    additionalDataSources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway
        access: proxy
        jsonData:
          httpMethod: GET
          maxLines: 1000
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: traceId=(\w*)
              name: traceId
              url: ${__value.raw}
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://observability-tempo:3200
        access: proxy
        jsonData:
          httpMethod: GET
          tracesToLogsV2:
            datasourceUid: loki
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true

# Custom subcharts
grafana:
  enabled: false

opentelemetry:
  enabled: true

kiali-server:
  enabled: true
  auth:
    strategy: anonymous
