{{- range $name, $config := .Values.services }}
---
# SPIFFE identity: cluster.local/ns/test/sa/{{ $name }}-sa
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        version: v1
    spec:
      serviceAccountName: {{ $name }}-sa
      containers:
        - name: {{ $name }}
          image: "{{ $config.image }}"
          imagePullPolicy: IfNotPresent
          {{- if $config.command }}
          command:
            {{- range $cmd := $config.command }}
            - {{ $cmd | quote }}
            {{- end }}
          {{- end }}
          {{- if $config.port }}
          ports:
            - name: http
              containerPort: {{ $config.port }}
          {{- end }}
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 64Mi
              cpu: 50m
{{- end }}
