{{- range $name, $config := .Values.services }}
{{- if $config.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.port }}
{{- end }}
{{- end }}
