{{/*
  ServiceAccount cho mỗi service.
  SPIFFE identity format: cluster.local/ns/<namespace>/sa/<serviceaccount-name>
  Đây là identity dùng trong AuthorizationPolicy principals.
*/}}

---
# SA cho product-svc
# SPIFFE: cluster.local/ns/test/sa/product-svc-sa
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-svc-sa
  namespace: {{ .Values.namespace }}

---
# SA cho order-svc
# SPIFFE: cluster.local/ns/test/sa/order-svc-sa
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-svc-sa
  namespace: {{ .Values.namespace }}

---
# SA cho sleep-client
# SPIFFE: cluster.local/ns/test/sa/sleep-client-sa
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleep-client-sa
  namespace: {{ .Values.namespace }}
