{{- range $name, $config := .Values.services }}
---
# SPIFFE: cluster.local/ns/{{ $.Values.namespace }}/sa/{{ $name }}-sa
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}-sa
  namespace: {{ $.Values.namespace }}
{{- end }}
