apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: yas
  namespace: argocd
spec:
  description: YAS GitOps project for multi-cluster deployment

  sourceRepos:
    - https://github.com/ducquan19/yas-gitops.git

  destinations:
    - namespace: yas-dev
      server: https://kubernetes.default.svc
    - namespace: yas-staging
      server: https://kubernetes.default.svc
    - namespace: yas-dev
      name: tbnguyen274
    - namespace: yas-staging
      name: tbnguyen274
    - namespace: yas-dev
      name: nqthang
    - namespace: yas-staging
      name: nqthang
    - namespace: yas-dev
      name: avocado2
    - namespace: yas-staging
      name: avocado2

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
