apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avocado2-staging
  namespace: argocd
spec:
  project: yas
  source:
    repoURL: https://github.com/ducquan19/yas-gitops.git
    targetRevision: staging
    path: helm/yas
    helm:
      valueFiles:
        - values.yaml
        - values-avocado2.yaml
        - values-staging.yaml
  destination:
    name: avocado2
    namespace: yas-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
