apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/ducquan19/yas-gitops.git
    targetRevision: HEAD
    path: helm/istio-demo
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    # Namespace được tạo bởi chart (namespace.yaml)
    # ArgoCD cần quyền tạo namespace hoặc namespace phải tồn tại trước
    namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   # ArgoCD tự tạo namespace nếu chưa có
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
