apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tdquan-dev
  namespace: argocd
spec:
  project: yas
  source:
    repoURL: https://github.com/ducquan19/yas-gitops.git
    targetRevision: main
    path: helm/yas
    helm:
      valueFiles:
        - values.yaml
        - values-tdquan.yaml
        - values-dev.yaml
  destination:
    server: https://100.88.234.42:8443
    namespace: yas-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
