apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry.fullname" . }}
  labels:
    {{- include "opentelemetry.labels" . | nindent 4 }}
data:
  collector.yaml: |
    {{- toYaml .Values.opentelemetryCollectorConfig | nindent 4 }}
