{{- range $serviceName, $serviceConfig := .Values }}
{{- if typeIs "map[string]interface {}" $serviceConfig }}
{{- if hasKey $serviceConfig "enabled" }}
{{- if and (eq $serviceConfig.enabled true) (hasKey $serviceConfig "image") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $serviceName }}
  template:
    metadata:
      labels:
        app: {{ $serviceName }}
    spec:
      serviceAccountName: {{ $serviceName }}-sa
      {{- if $serviceConfig.isBackend }}
      volumes:
        - name: yas-configuration
          configMap:
            name: yas-configuration-configmap
        {{- if contains "bff" $serviceName }}
        - name: yas-gateway-routes-config
          configMap:
            name: yas-gateway-routes-config
        {{- end }}
      {{- end }}
      containers:
        - name: {{ $serviceName }}
          image: "{{ $serviceConfig.image.repository }}:{{ $serviceConfig.image.tag }}"
          imagePullPolicy: IfNotPresent
          {{- if $serviceConfig.service }}
          ports:
            - containerPort: {{ default $serviceConfig.service.port $serviceConfig.image.containerPort }}
          {{- end }}
          {{- if $serviceConfig.isBackend }}
          volumeMounts:
            - mountPath: /opt/yas/config
              name: yas-configuration
            {{- if contains "bff" $serviceName }}
            - mountPath: /opt/yas/gateway-routes-config
              name: yas-gateway-routes-config
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml $serviceConfig.resources | nindent 12 }}
          {{- if or $serviceConfig.env $serviceConfig.secrets $serviceConfig.isBackend }}
          envFrom:
            {{- if $serviceConfig.isBackend }}
            - secretRef:
                name: yas-postgresql-credentials-secret
            {{- end }}
            {{- if $serviceConfig.env }}
            - configMapRef:
                name: {{ $serviceName }}-config
            {{- end }}
            {{- if $serviceConfig.secrets }}
            - secretRef:
                name: {{ $serviceName }}-secret
            {{- end }}
          {{- end }}
          {{- if $serviceConfig.isBackend }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SERVER_PORT
              value: {{ $serviceConfig.service.port | quote }}
            - name: LOGGING_CONFIG
              value: /opt/yas/config/logback.xml
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://infrastructure-postgresql:5432/{{ $serviceName }}
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: /opt/yas/config/application.yaml{{- if contains "bff" $serviceName }},/opt/yas/gateway-routes-config/gateway-routes.yaml{{- end }}
            {{- if $serviceConfig.uiHost }}
            - name: UI_HOST
              value: {{ $serviceConfig.uiHost | quote }}
            {{- end }}
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
