{{- if .Values.swagger.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yas-openapi-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1/v3/api-docs
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.{{ .Values.global.domain | default "yas.io" }}
      secretName: yas-tls-secret
  rules:
    - host: api.{{ .Values.global.domain | default "yas.io" }}
      http:
        paths:
{{- range $svcName := list "product" "cart" "order" "customer" "media" "inventory" "search" "tax" "payment" "rating" "recommendation" "location" }}
          - path: /api/({{ $svcName }})/v3/api-docs
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: 8082
{{- end }}
          - path: /api/(sampledata)/v3/api-docs
            pathType: ImplementationSpecific
            backend:
              service:
                name: sampledata
                port:
                  number: 8094
{{- end }}
