apiVersion: v1
kind: Secret
metadata:
  name: yas-postgresql-credentials-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRESQL_USERNAME: {{ .Values.global.postgresql.username | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.global.postgresql.password | quote }}
