{{- range $serviceName, $serviceConfig := .Values }}
{{- if typeIs "map[string]interface {}" $serviceConfig }}
{{- if hasKey $serviceConfig "enabled" }}
{{- if and (eq $serviceConfig.enabled true) (hasKey $serviceConfig "image") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}-sa
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
