{{- if .Values.swagger.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yas-swagger-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.{{ .Values.global.domain | default "yas.io" }}
      secretName: yas-tls-secret
  rules:
    - host: api.{{ .Values.global.domain | default "yas.io" }}
      http:
        paths:
          - path: /()(swagger-ui.css|index.css|swagger-ui-bundle.js|swagger-ui-standalone-preset.js|swagger-initializer.js|oauth2-redirect.html|favicon-16x16.png|favicon-32x32.png)
            pathType: ImplementationSpecific
            backend:
              service:
                name: swagger
                port:
                  number: 8080
          - path: /swagger-ui(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: swagger
                port:
                  number: 8080
{{- end }}
