apiVersion: v1
kind: ConfigMap
metadata:
  name: yas-configuration-configmap
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |
    server:
      shutdown: graceful
      port: 80

    management:
      otlp:
        tracing:
          endpoint: http://opentelemetry-collector.observability:4318/v1/traces
      server:
        port: 8090
      health:
        readinessstate:
          enabled: true
        livenessstate:
          enabled: true
      tracing:
        sampling:
          probability: 1.0
      metrics:
        tags:
          application: ${spring.application.name}
      endpoints:
        web:
          exposure:
            include: prometheus, health
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always

    logging:
      pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

    spring:
      lifecycle:
        timeout-per-shutdown-phase: 30s
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: http://infra-keycloak.infrastructure.svc.cluster.local/realms/Yas/protocol/openid-connect/certs
          client:
            provider:
              keycloak:
                authorization-uri: https://identity.{{ .Values.global.domain | default "yas.io" }}/realms/Yas/protocol/openid-connect/auth
                token-uri: http://infra-keycloak.infrastructure.svc.cluster.local/realms/Yas/protocol/openid-connect/token
                jwk-set-uri: http://infra-keycloak.infrastructure.svc.cluster.local/realms/Yas/protocol/openid-connect/certs
                user-info-uri: http://infra-keycloak.infrastructure.svc.cluster.local/realms/Yas/protocol/openid-connect/userinfo
                user-name-attribute: preferred_username
            registration:
              keycloak:
                provider: keycloak
                client-id: storefront-bff
                client-secret: ZrU9I0q2uXBglBnmvyJdkl1lf0ncr8tn #gitleaks:allow
                scope: openid, profile, email, roles
                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
              api-client:
                provider: keycloak
                client-id: backoffice-bff
                client-secret: TVacLC0cQ8tiiEKiTVerTb2YvwQ1TRJF #gitleaks:allow
                scope: openid, profile, email, roles
                redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

      datasource:
        username: {{ .Values.global.postgresql.username }}
        password: {{ .Values.global.postgresql.password }}
      kafka:
        bootstrap-servers: {{ .Values.global.kafka.bootstrapServers }}
        consumer:
          bootstrap-servers: {{ .Values.global.kafka.bootstrapServers }}
        producer:
          bootstrap-servers: {{ .Values.global.kafka.bootstrapServers }}
      data:
        redis:
          host: {{ .Values.global.redis.host }}
          port: {{ .Values.global.redis.port }}
      elasticsearch:
        uris: {{ .Values.global.elasticsearch.uris }}

    elasticsearch:
      url: infra-elasticsearch.infrastructure.svc.cluster.local:9200

    springdoc:
      oauthflow:
        authorization-url: https://identity.{{ .Values.global.domain | default "yas.io" }}/realms/Yas/protocol/openid-connect/auth
        token-url: https://identity.{{ .Values.global.domain | default "yas.io" }}/realms/Yas/protocol/openid-connect/token

    yas:
      publicUrl: /api/media
      services:
        cart: http://cart:8082/cart
        customer: http://customer:8082/customer
        inventory: http://inventory:8082/inventory
        location: http://location:8082/location
        media: http://media:8082
        order: http://order:8082/order
        payment: http://payment:8082/payment
        payment-paypal: http://payment-paypal:8082/payment-paypal
        product: http://product:8082/product
        promotion: http://promotion:8082/promotion
        rating: http://rating:8082/rating
        search: http://search:8082/search
        tax: http://tax:8082/tax
        sampledata: http://sampledata:8094/sampledata
        recommendation: http://recommendation:8082/recommendation
        token-identity: http://infra-keycloak.infrastructure.svc.cluster.local/realms/Yas/protocol/openid-connect/token

    file:
      directory: /tmp

  logback.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration>
        <include resource="org/springframework/boot/logging/logback/defaults.xml" />
        <include resource="org/springframework/boot/logging/logback/console-appender.xml" />
        <property name="LOG_LEVEL" value="${LOG_LEVEL:-INFO}"/>
        <root level="INFO">
            <appender-ref ref="CONSOLE" />
        </root>
        <logger name="com.yas" level="${LOG_LEVEL}" additivity="false">
            <appender-ref ref="CONSOLE" />
        </logger>
    </Configuration>
