apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-postgresql-init
  namespace: {{ .Release.Namespace }}
data:
  init-databases.sql: |
    CREATE DATABASE product;
    CREATE DATABASE inventory;
    CREATE DATABASE search;
    CREATE DATABASE media;
    CREATE DATABASE cart;
    CREATE DATABASE customer;
    CREATE DATABASE "order";
    CREATE DATABASE payment;
    CREATE DATABASE promotion;
    CREATE DATABASE rating;
    CREATE DATABASE tax;
    CREATE DATABASE recommendation;
    CREATE DATABASE webhook;
    CREATE DATABASE sampledata;
    CREATE DATABASE grafana;
    CREATE DATABASE keycloak;
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infra-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "infra-postgresql"
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: "debezium/postgres:16-alpine"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d/init-databases.sql
          subPath: init-databases.sql
      volumes:
      - name: init-scripts
        configMap:
          name: infra-postgresql-init
  volumeClaimTemplates:
  - metadata:
      name: pg-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: infra-postgresql
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
